language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install -y gcc libssl-dev openssl libcurl4-gnutls-dev libcrypto++-dev libssl1.0.0 ca-certificates
install:
  - python setup.py -q install
# command to run tests
script: pytest tests/test.py
